spring:
  datasource:
    url: jdbc:postgresql://${DB_PRESS_HOST:localhost}:${DB_PRESS_PORT:5432}/${DB_PRESS_NAME:post-service-db}
    username: ${DB_PRESS_USERNAME:post-service}
    password: ${DB_PRESS_PASSWORD:password1234}
    hikari:
      idle-timeout: 300000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        show_sql: true
#        use_sql_comments: true
#        format_sql: true
